apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-cu-cnfde2-sriov-network
  namespace: cu-cnfde2-subscription
placementRef:
  name: placement-policy-cu-cnfde2-sriov-network
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-cu-cnfde2-sriov-network
  kind: Policy
  apiGroup: policy.open-cluster-management.io
