apiVersion: v1
kind: Namespace
metadata:
<<<<<<< HEAD:spoke_clusters/.yaml
  name: cu-cnfde2-cluster
=======
  name: sample-site-cu-cluster
>>>>>>> 4bf835a469919a7a0349848c326508971193ecef:spoke_clusters/01_sample_cu_cluster.yaml
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
<<<<<<< HEAD:spoke_clusters/.yaml
    name: cu-cnfde2-cluster
    profile: cu
  name: cu-cnfde2-cluster
=======
    name: sample-site-cu-cluster
    profile: cu
  name: sample-site-cu-cluster
>>>>>>> 4bf835a469919a7a0349848c326508971193ecef:spoke_clusters/01_sample_cu_cluster.yaml
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
<<<<<<< HEAD:spoke_clusters/.yaml
  name: cu-cnfde2-cluster
  namespace: cu-cnfde2-cluster
spec:
  clusterName: cu-cnfde2-cluster
  clusterNamespace: cu-cnfde2-cluster
=======
  name: sample-site-cu-cluster
  namespace: sample-site-cu-cluster
spec:
  clusterName: sample-site-cu-cluster
  clusterNamespace: sample-site-cu-cluster
>>>>>>> 4bf835a469919a7a0349848c326508971193ecef:spoke_clusters/01_sample_cu_cluster.yaml
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  version: 2.1.0
